import Header from '@/components/Header';
import './globals.css'
import { Open_Sans } from 'next/font/google';
import AuthContext from '@/context/AuthContext';

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className='flex flex-col w-full h-full mx-auto'>
        <AuthContext>
          <Header/>
          <main className='ml-8 mr-8 m-auto w-full h-ull'>{children}</main>
        </AuthContext>
      </body>
    </html>
  )
}
