import Header from '@/components/Header';
import './globals.css'
import { Open_Sans } from 'next/font/google';
import AuthContext from '@/context/AuthContext';
import SWRConfigContext from '@/context/SWRConfigContext';



const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className='w-full overflow-auto bg-neutral-50'>
        <AuthContext>
        <header className='sticky top-0 bg-white z-10 border-b'>
            <div className='max-w-screen-xl mx-auto'>
              <Header/>
            </div>
          </header>
          <main className='w-full flex justify-center'>
            <SWRConfigContext>
              {children}
            </SWRConfigContext>
          </main>
        </AuthContext>
        {/* 여기에 portal 보여줄거임 */}
        <div id='portal'/>
      </body>
    </html>
  )
}
